name: cheese-daily
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - requests
  - pandas
  - numpy
  - beautifulsoup4
  - lxml
  - selenium
  - openai
  - anthropic
  - arxiv
  - qiskit
